import "./globals.css";
import SideNav from "@/components/SideNav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`no-scrollbar grid place-content-center bg-white  overflow-x-hidden  `}
      >
        {children}
      </body>
    </html>
  );
}
